"""
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.querybuilder_rule_group_schema import QuerybuilderRuleGroupSchema


class TestQuerybuilderRuleGroupSchema(unittest.TestCase):
    """QuerybuilderRuleGroupSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuerybuilderRuleGroupSchema(self):
        """Test QuerybuilderRuleGroupSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuerybuilderRuleGroupSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
