# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.cmspb_frontend_configuration_objective import CmspbFrontendConfigurationObjective

class TestCmspbFrontendConfigurationObjective(unittest.TestCase):
    """CmspbFrontendConfigurationObjective unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmspbFrontendConfigurationObjective:
        """Test CmspbFrontendConfigurationObjective
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmspbFrontendConfigurationObjective`
        """
        model = CmspbFrontendConfigurationObjective()
        if include_optional:
            return CmspbFrontendConfigurationObjective(
                attackers_perspective = '',
                description = '',
                implication = ''
            )
        else:
            return CmspbFrontendConfigurationObjective(
        )
        """

    def testCmspbFrontendConfigurationObjective(self):
        """Test CmspbFrontendConfigurationObjective"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
