# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import randori_api
from randori_api.models.ip import Ip  # noqa: E501
from randori_api.rest import ApiException

class TestIp(unittest.TestCase):
    """Ip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Ip
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = randori_api.models.ip.Ip()  # noqa: E501
        if include_optional :
            return Ip(
                affiliation_state = 'None', 
                all_ports = [
                    None
                    ], 
                confidence = 56, 
                country = '0', 
                deleted = True, 
                first_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                hostname_count = 56, 
                id = '0', 
                impact_score = 'None', 
                ip = '0', 
                ip_str = '0', 
                last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                latitude = 1.337, 
                lens_id = '0', 
                lens_view = '0', 
                longitude = 1.337, 
                only_in_review_targets = True, 
                open_port_count = 56, 
                org_id = '0', 
                perspective = '0', 
                perspective_name = '0', 
                priority_impact_factor = 1.337, 
                priority_score = 1.337, 
                priority_status_factor = 1.337, 
                priority_tags_factor = 1.337, 
                radius = 1.337, 
                service_count = 56, 
                status = 'None', 
                tags = randori_api.models.tags.tags(), 
                target_count = 56, 
                target_temptation = 56
            )
        else :
            return Ip(
                id = '0',
                org_id = '0',
        )

    def testIp(self):
        """Test Ip"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
