# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.cmspb_frontend_parameters_response import CmspbFrontendParametersResponse

class TestCmspbFrontendParametersResponse(unittest.TestCase):
    """CmspbFrontendParametersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmspbFrontendParametersResponse:
        """Test CmspbFrontendParametersResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmspbFrontendParametersResponse`
        """
        model = CmspbFrontendParametersResponse()
        if include_optional:
            return CmspbFrontendParametersResponse(
                data = [
                    randori_api_sdk.models.cmspb/frontend_parameter_object.cmspb.FrontendParameterObject(
                        attributes = randori_api_sdk.models.cmspb/frontend_parameter.cmspb.FrontendParameter(
                            description = '', 
                            field_label = '', 
                            field_type = '', 
                            is_configurable = True, 
                            is_not_set = True, 
                            is_optional = True, 
                            parameter = '', 
                            parameter_type = 0, 
                            validation = randori_api_sdk.models.cmspb/frontend_validation.cmspb.FrontendValidation(
                                error_text = '', 
                                kind = '', 
                                value = '', ), 
                            value = randori_api_sdk.models.structpb/value.structpb.Value(
                                kind = null, ), ), 
                        type = 0, )
                    ],
                links = randori_api_sdk.models.cmspb/frontend_links.cmspb.FrontendLinks(
                    last = '', 
                    next = '', 
                    self = '', ),
                meta = randori_api_sdk.models.cmspb/frontend_meta.cmspb.FrontendMeta(
                    count = 56, 
                    offset = 56, 
                    total = 56, )
            )
        else:
            return CmspbFrontendParametersResponse(
        )
        """

    def testCmspbFrontendParametersResponse(self):
        """Test CmspbFrontendParametersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
