# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.cms_validate_now_request import CmsValidateNowRequest

class TestCmsValidateNowRequest(unittest.TestCase):
    """CmsValidateNowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmsValidateNowRequest:
        """Test CmsValidateNowRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmsValidateNowRequest`
        """
        model = CmsValidateNowRequest()
        if include_optional:
            return CmsValidateNowRequest(
                configuration_id = '',
                entity_id = '',
                entity_type = ''
            )
        else:
            return CmsValidateNowRequest(
        )
        """

    def testCmsValidateNowRequest(self):
        """Test CmsValidateNowRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
