"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.peer_single_output_data import PeerSingleOutputData
globals()['PeerSingleOutputData'] = PeerSingleOutputData
from randori_api.model.peer_single_output import PeerSingleOutput


class TestPeerSingleOutput(unittest.TestCase):
    """PeerSingleOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeerSingleOutput(self):
        """Test PeerSingleOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeerSingleOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
