# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.ip import Ip

class TestIp(unittest.TestCase):
    """Ip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ip:
        """Test Ip
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ip`
        """
        model = Ip()
        if include_optional:
            return Ip(
                affiliation_state = 'None',
                all_ports = [
                    None
                    ],
                authority = True,
                authority_distance = 56,
                authority_override = True,
                characteristic_tags = [
                    ''
                    ],
                confidence = 56,
                country = '',
                deleted = True,
                first_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hostname_count = 56,
                hostnames = [
                    ''
                    ],
                id = '',
                impact_score = 'None',
                ip = '',
                ip_str = '',
                last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                latitude = 1.337,
                lens_id = '',
                lens_view = '',
                longitude = 1.337,
                only_in_review_targets = True,
                open_port_count = 56,
                org_id = '',
                perspective = '',
                perspective_name = '',
                priority_impact_factor = 1.337,
                priority_score = 1.337,
                priority_status_factor = 1.337,
                priority_tags_factor = 1.337,
                radius = 1.337,
                service_count = 56,
                status = 'None',
                target_count = 56,
                target_temptation = 56,
                user_tags = [
                    ''
                    ]
            )
        else:
            return Ip(
                id = '',
                org_id = '',
        )
        """

    def testIp(self):
        """Test Ip"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
