"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.attack_user_autoapprove_patch_in import AttackUserAutoapprovePatchIn
globals()['AttackUserAutoapprovePatchIn'] = AttackUserAutoapprovePatchIn
from randori_api.model.attack_user_autoapprove_patch_single_input_data import AttackUserAutoapprovePatchSingleInputData


class TestAttackUserAutoapprovePatchSingleInputData(unittest.TestCase):
    """AttackUserAutoapprovePatchSingleInputData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackUserAutoapprovePatchSingleInputData(self):
        """Test AttackUserAutoapprovePatchSingleInputData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackUserAutoapprovePatchSingleInputData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
