"""
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.attack_user_runbook_descriptions_post_output import AttackUserRunbookDescriptionsPostOutput


class TestAttackUserRunbookDescriptionsPostOutput(unittest.TestCase):
    """AttackUserRunbookDescriptionsPostOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackUserRunbookDescriptionsPostOutput(self):
        """Test AttackUserRunbookDescriptionsPostOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackUserRunbookDescriptionsPostOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
