# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import randori_api
from randori_api.models.service_get_output import ServiceGetOutput  # noqa: E501
from randori_api.rest import ApiException


class TestServiceGetOutput(unittest.TestCase):
    """ServiceGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceGetOutput(self):
        """Test ServiceGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = randori_api.models.service_get_output.ServiceGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
