# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import randori_api
from randori_api.models.network_get_output import NetworkGetOutput  # noqa: E501
from randori_api.rest import ApiException


class TestNetworkGetOutput(unittest.TestCase):
    """NetworkGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkGetOutput(self):
        """Test NetworkGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = randori_api.models.network_get_output.NetworkGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
