# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.cmspb_frontend_single_parameter_response import CmspbFrontendSingleParameterResponse

class TestCmspbFrontendSingleParameterResponse(unittest.TestCase):
    """CmspbFrontendSingleParameterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmspbFrontendSingleParameterResponse:
        """Test CmspbFrontendSingleParameterResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmspbFrontendSingleParameterResponse`
        """
        model = CmspbFrontendSingleParameterResponse()
        if include_optional:
            return CmspbFrontendSingleParameterResponse(
                data = randori_api_sdk.models.cmspb/frontend_parameter_object.cmspb.FrontendParameterObject(
                    attributes = randori_api_sdk.models.cmspb/frontend_parameter.cmspb.FrontendParameter(
                        description = '', 
                        field_label = '', 
                        field_type = '', 
                        is_configurable = True, 
                        is_not_set = True, 
                        is_optional = True, 
                        parameter = '', 
                        parameter_type = 0, 
                        validation = randori_api_sdk.models.cmspb/frontend_validation.cmspb.FrontendValidation(
                            error_text = '', 
                            kind = '', 
                            value = '', ), 
                        value = randori_api_sdk.models.structpb/value.structpb.Value(
                            kind = null, ), ), 
                    type = 0, )
            )
        else:
            return CmspbFrontendSingleParameterResponse(
        )
        """

    def testCmspbFrontendSingleParameterResponse(self):
        """Test CmspbFrontendSingleParameterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
