"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.all_detections_for_target import AllDetectionsForTarget
globals()['AllDetectionsForTarget'] = AllDetectionsForTarget
from randori_api.model.all_detections_for_target_get_output import AllDetectionsForTargetGetOutput


class TestAllDetectionsForTargetGetOutput(unittest.TestCase):
    """AllDetectionsForTargetGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllDetectionsForTargetGetOutput(self):
        """Test AllDetectionsForTargetGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AllDetectionsForTargetGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
