# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.hostnames_for_ip_get_output import HostnamesForIpGetOutput

class TestHostnamesForIpGetOutput(unittest.TestCase):
    """HostnamesForIpGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostnamesForIpGetOutput:
        """Test HostnamesForIpGetOutput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostnamesForIpGetOutput`
        """
        model = HostnamesForIpGetOutput()
        if include_optional:
            return HostnamesForIpGetOutput(
                count = 56,
                data = [
                    randori_api_sdk.models.hostnames_for_ip.hostnames-for-ip(
                        affiliation_state = 'None', 
                        confidence = 56, 
                        deleted = True, 
                        hostname = '', 
                        hostname_id = '', 
                        id = '', 
                        impact_score = 'None', 
                        ip_id = '', 
                        last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        lens_id = '', 
                        lens_view = '', 
                        org_id = '', 
                        perspective = '', 
                        perspective_name = '', 
                        status = 'None', )
                    ],
                offset = 56,
                total = 56
            )
        else:
            return HostnamesForIpGetOutput(
        )
        """

    def testHostnamesForIpGetOutput(self):
        """Test HostnamesForIpGetOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
