# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import randori_api
from randori_api.models.ips_for_service_get_output import IpsForServiceGetOutput  # noqa: E501
from randori_api.rest import ApiException


class TestIpsForServiceGetOutput(unittest.TestCase):
    """IpsForServiceGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIpsForServiceGetOutput(self):
        """Test IpsForServiceGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = randori_api.models.ips_for_service_get_output.IpsForServiceGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
