"""
© Copyright IBM Corp. 2022
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.policy_post_output import PolicyPostOutput


class TestPolicyPostOutput(unittest.TestCase):
    """PolicyPostOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyPostOutput(self):
        """Test PolicyPostOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PolicyPostOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
