"""
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.ips_for_hostname import IpsForHostname
globals()['IpsForHostname'] = IpsForHostname
from randori_api.model.ips_for_hostname_get_output import IpsForHostnameGetOutput


class TestIpsForHostnameGetOutput(unittest.TestCase):
    """IpsForHostnameGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIpsForHostnameGetOutput(self):
        """Test IpsForHostnameGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IpsForHostnameGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
