# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import randori_api
from randori_api.models.saved_views_post_input import SavedViewsPostInput  # noqa: E501
from randori_api.rest import ApiException

class TestSavedViewsPostInput(unittest.TestCase):
    """SavedViewsPostInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SavedViewsPostInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = randori_api.models.saved_views_post_input.SavedViewsPostInput()  # noqa: E501
        if include_optional :
            return SavedViewsPostInput(
                data = [
                    randori_api.models.saved_views_model_custom_in.saved-views-model-custom-in(
                        description = '0', 
                        entity_type = 'target', 
                        filter_data = randori_api.models.filter_data.filter_data(), 
                        name = '0', 
                        sort_data = randori_api.models.sort_data.sort_data(), )
                    ]
            )
        else :
            return SavedViewsPostInput(
        )

    def testSavedViewsPostInput(self):
        """Test SavedViewsPostInput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
