"""
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.attack_user_action_descriptions_patch_in import AttackUserActionDescriptionsPatchIn
globals()['AttackUserActionDescriptionsPatchIn'] = AttackUserActionDescriptionsPatchIn
from randori_api.model.attack_user_action_descriptions_patch_single_input_data import AttackUserActionDescriptionsPatchSingleInputData


class TestAttackUserActionDescriptionsPatchSingleInputData(unittest.TestCase):
    """AttackUserActionDescriptionsPatchSingleInputData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackUserActionDescriptionsPatchSingleInputData(self):
        """Test AttackUserActionDescriptionsPatchSingleInputData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackUserActionDescriptionsPatchSingleInputData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
