"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.service import Service
globals()['Service'] = Service
from randori_api.model.service_get_output import ServiceGetOutput


class TestServiceGetOutput(unittest.TestCase):
    """ServiceGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceGetOutput(self):
        """Test ServiceGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
