# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import randori_api
from randori_api.models.hostnames_for_ip_get_output import HostnamesForIpGetOutput  # noqa: E501
from randori_api.rest import ApiException


class TestHostnamesForIpGetOutput(unittest.TestCase):
    """HostnamesForIpGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostnamesForIpGetOutput(self):
        """Test HostnamesForIpGetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = randori_api.models.hostnames_for_ip_get_output.HostnamesForIpGetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
