"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.target_single_output_data import TargetSingleOutputData
globals()['TargetSingleOutputData'] = TargetSingleOutputData
from randori_api.model.target_single_output import TargetSingleOutput


class TestTargetSingleOutput(unittest.TestCase):
    """TargetSingleOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTargetSingleOutput(self):
        """Test TargetSingleOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TargetSingleOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
