"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.peer_post_output import PeerPostOutput


class TestPeerPostOutput(unittest.TestCase):
    """PeerPostOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeerPostOutput(self):
        """Test PeerPostOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeerPostOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
