"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.attack_user_runbook_descriptions_model_in import AttackUserRunbookDescriptionsModelIn


class TestAttackUserRunbookDescriptionsModelIn(unittest.TestCase):
    """AttackUserRunbookDescriptionsModelIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackUserRunbookDescriptionsModelIn(self):
        """Test AttackUserRunbookDescriptionsModelIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackUserRunbookDescriptionsModelIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
