# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from randori_api_sdk.models.cmspb_frontend_type import CmspbFrontendType

class TestCmspbFrontendType(unittest.TestCase):
    """CmspbFrontendType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCmspbFrontendType(self):
        """Test CmspbFrontendType"""
        # inst = CmspbFrontendType()

if __name__ == '__main__':
    unittest.main()
