# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import randori_api
from randori_api.models.paths_data_schema import PathsDataSchema  # noqa: E501
from randori_api.rest import ApiException

class TestPathsDataSchema(unittest.TestCase):
    """PathsDataSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PathsDataSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = randori_api.models.paths_data_schema.PathsDataSchema()  # noqa: E501
        if include_optional :
            return PathsDataSchema(
                edges = {
                    'key' : randori_api.models.edge_schema.edge_schema(
                        content = randori_api.models.content.content(), 
                        dst = '0', 
                        id = '0', 
                        src = '0', 
                        type = '0', )
                    }, 
                nodes = {
                    'key' : randori_api.models.node_schema.node_schema(
                        content = randori_api.models.content.content(), 
                        id = '0', 
                        type = '0', )
                    }, 
                paths = [
                    [
                        '0'
                        ]
                    ]
            )
        else :
            return PathsDataSchema(
        )

    def testPathsDataSchema(self):
        """Test PathsDataSchema"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
