"""
© Copyright IBM Corp. 2022
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.attack_user_autoapprove_patch_single_input_data import AttackUserAutoapprovePatchSingleInputData
globals()['AttackUserAutoapprovePatchSingleInputData'] = AttackUserAutoapprovePatchSingleInputData
from randori_api.model.attack_user_autoapprove_patch_single_input import AttackUserAutoapprovePatchSingleInput


class TestAttackUserAutoapprovePatchSingleInput(unittest.TestCase):
    """AttackUserAutoapprovePatchSingleInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackUserAutoapprovePatchSingleInput(self):
        """Test AttackUserAutoapprovePatchSingleInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackUserAutoapprovePatchSingleInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
