"""
Copyright © 2022 Randori https://randori.com - All Rights Reserved.
"""

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import randori_api
from randori_api.model.report import Report
globals()['Report'] = Report
from randori_api.model.report_single_output_data import ReportSingleOutputData


class TestReportSingleOutputData(unittest.TestCase):
    """ReportSingleOutputData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportSingleOutputData(self):
        """Test ReportSingleOutputData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportSingleOutputData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
