# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from randori_api_sdk.models.cmspb_settings_criteria import CmspbSettingsCriteria
from randori_api_sdk.models.cmspb_settings_parameter import CmspbSettingsParameter
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CmspbSettings(BaseModel):
    """
    CmspbSettings
    """ # noqa: E501
    execution_parameters: Optional[List[CmspbSettingsParameter]] = None
    matching_criteria: Optional[List[CmspbSettingsCriteria]] = None
    parameters: Optional[List[CmspbSettingsParameter]] = None
    trigger_criteria: Optional[List[CmspbSettingsCriteria]] = None
    __properties: ClassVar[List[str]] = ["execution_parameters", "matching_criteria", "parameters", "trigger_criteria"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CmspbSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in execution_parameters (list)
        _items = []
        if self.execution_parameters:
            for _item in self.execution_parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['execution_parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in matching_criteria (list)
        _items = []
        if self.matching_criteria:
            for _item in self.matching_criteria:
                if _item:
                    _items.append(_item.to_dict())
            _dict['matching_criteria'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item in self.parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in trigger_criteria (list)
        _items = []
        if self.trigger_criteria:
            for _item in self.trigger_criteria:
                if _item:
                    _items.append(_item.to_dict())
            _dict['trigger_criteria'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CmspbSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "execution_parameters": [CmspbSettingsParameter.from_dict(_item) for _item in obj.get("execution_parameters")] if obj.get("execution_parameters") is not None else None,
            "matching_criteria": [CmspbSettingsCriteria.from_dict(_item) for _item in obj.get("matching_criteria")] if obj.get("matching_criteria") is not None else None,
            "parameters": [CmspbSettingsParameter.from_dict(_item) for _item in obj.get("parameters")] if obj.get("parameters") is not None else None,
            "trigger_criteria": [CmspbSettingsCriteria.from_dict(_item) for _item in obj.get("trigger_criteria")] if obj.get("trigger_criteria") is not None else None
        })
        return _obj


