# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from randori_api_sdk.models.json_patch_operation import JsonPatchOperation
from randori_api_sdk.models.network_patch_in import NetworkPatchIn
from randori_api_sdk.models.querybuilder_rule_group_schema import QuerybuilderRuleGroupSchema
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NetworkPatchInput(BaseModel):
    """
    NetworkPatchInput
    """ # noqa: E501
    data: Optional[NetworkPatchIn] = None
    operations: Optional[List[JsonPatchOperation]] = None
    q: Optional[QuerybuilderRuleGroupSchema] = None
    __properties: ClassVar[List[str]] = ["data", "operations", "q"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkPatchInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in operations (list)
        _items = []
        if self.operations:
            for _item in self.operations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['operations'] = _items
        # override the default output from pydantic by calling `to_dict()` of q
        if self.q:
            _dict['q'] = self.q.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NetworkPatchInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": NetworkPatchIn.from_dict(obj.get("data")) if obj.get("data") is not None else None,
            "operations": [JsonPatchOperation.from_dict(_item) for _item in obj.get("operations")] if obj.get("operations") is not None else None,
            "q": QuerybuilderRuleGroupSchema.from_dict(obj.get("q")) if obj.get("q") is not None else None
        })
        return _obj


