# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from randori_api_sdk.models.path_dr_schema import PathDrSchema
from randori_api_sdk.models.path_entity_schema import PathEntitySchema
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PathsDataSchema(BaseModel):
    """
    PathsDataSchema
    """ # noqa: E501
    edges: Optional[Dict[str, PathDrSchema]] = None
    nodes: Optional[Dict[str, PathEntitySchema]] = None
    paths: Optional[List[List[StrictStr]]] = None
    __properties: ClassVar[List[str]] = ["edges", "nodes", "paths"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PathsDataSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in edges (dict)
        _field_dict = {}
        if self.edges:
            for _key in self.edges:
                if self.edges[_key]:
                    _field_dict[_key] = self.edges[_key].to_dict()
            _dict['edges'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in nodes (dict)
        _field_dict = {}
        if self.nodes:
            for _key in self.nodes:
                if self.nodes[_key]:
                    _field_dict[_key] = self.nodes[_key].to_dict()
            _dict['nodes'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PathsDataSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "edges": dict(
                (_k, PathDrSchema.from_dict(_v))
                for _k, _v in obj.get("edges").items()
            )
            if obj.get("edges") is not None
            else None,
            "nodes": dict(
                (_k, PathEntitySchema.from_dict(_v))
                for _k, _v in obj.get("nodes").items()
            )
            if obj.get("nodes") is not None
            else None,
            "paths": obj.get("paths")
        })
        return _obj


