# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, field_validator
from pydantic import Field
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserPatchIn(BaseModel):
    """
    UserPatchIn
    """ # noqa: E501
    email: Optional[StrictStr] = None
    managed_personnel: Optional[StrictBool] = None
    name: Optional[Annotated[str, Field(strict=True)]] = None
    title: Optional[Annotated[str, Field(strict=True)]] = None
    tos_date: Optional[datetime] = None
    tos_version: Optional[StrictInt] = None
    username: Optional[Annotated[str, Field(strict=True)]] = None
    view_org: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["email", "managed_personnel", "name", "title", "tos_date", "tos_version", "username", "view_org"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\\@#$%ˆ&*(){}|~<>;:[\]`]{1,80}$", value):
            raise ValueError(r"must validate the regular expression /^[^\\@#$%ˆ&*(){}|~<>;:[\]`]{1,80}$/")
        return value

    @field_validator('title')
    def title_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\\@#$%ˆ*(){}|~<>;:[\]`]{1,80}$", value):
            raise ValueError(r"must validate the regular expression /^[^\\@#$%ˆ*(){}|~<>;:[\]`]{1,80}$/")
        return value

    @field_validator('username')
    def username_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[\w@.\d_+-]{1,80}$", value):
            raise ValueError(r"must validate the regular expression /^[\w@.\d_+-]{1,80}$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserPatchIn from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if managed_personnel (nullable) is None
        # and model_fields_set contains the field
        if self.managed_personnel is None and "managed_personnel" in self.model_fields_set:
            _dict['managed_personnel'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if view_org (nullable) is None
        # and model_fields_set contains the field
        if self.view_org is None and "view_org" in self.model_fields_set:
            _dict['view_org'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserPatchIn from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "managed_personnel": obj.get("managed_personnel"),
            "name": obj.get("name"),
            "title": obj.get("title"),
            "tos_date": obj.get("tos_date"),
            "tos_version": obj.get("tos_version"),
            "username": obj.get("username"),
            "view_org": obj.get("view_org")
        })
        return _obj


