# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from randori_api.configuration import Configuration


class Hostname(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'confidence': 'int',
        'deleted': 'bool',
        'first_seen': 'datetime',
        'hostname': 'str',
        'id': 'str',
        'ip_count': 'int',
        'is_prime': 'bool',
        'last_seen': 'datetime',
        'max_confidence': 'int',
        'name_type': 'int',
        'org_id': 'str',
        'perspective': 'str',
        'perspective_name': 'str',
        'status': 'str',
        'tags': 'object',
        'target_temptation': 'int'
    }

    attribute_map = {
        'confidence': 'confidence',
        'deleted': 'deleted',
        'first_seen': 'first_seen',
        'hostname': 'hostname',
        'id': 'id',
        'ip_count': 'ip_count',
        'is_prime': 'is_prime',
        'last_seen': 'last_seen',
        'max_confidence': 'max_confidence',
        'name_type': 'name_type',
        'org_id': 'org_id',
        'perspective': 'perspective',
        'perspective_name': 'perspective_name',
        'status': 'status',
        'tags': 'tags',
        'target_temptation': 'target_temptation'
    }

    def __init__(self, confidence=None, deleted=None, first_seen=None, hostname=None, id=None, ip_count=None, is_prime=None, last_seen=None, max_confidence=None, name_type=None, org_id=None, perspective=None, perspective_name=None, status=None, tags=None, target_temptation=None, local_vars_configuration=None):  # noqa: E501
        """Hostname - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._confidence = None
        self._deleted = None
        self._first_seen = None
        self._hostname = None
        self._id = None
        self._ip_count = None
        self._is_prime = None
        self._last_seen = None
        self._max_confidence = None
        self._name_type = None
        self._org_id = None
        self._perspective = None
        self._perspective_name = None
        self._status = None
        self._tags = None
        self._target_temptation = None
        self.discriminator = None

        self.confidence = confidence
        if deleted is not None:
            self.deleted = deleted
        self.first_seen = first_seen
        self.hostname = hostname
        self.id = id
        self.ip_count = ip_count
        self.is_prime = is_prime
        self.last_seen = last_seen
        self.max_confidence = max_confidence
        self.name_type = name_type
        self.org_id = org_id
        self.perspective = perspective
        self.perspective_name = perspective_name
        if status is not None:
            self.status = status
        self.tags = tags
        self.target_temptation = target_temptation

    @property
    def confidence(self):
        """Gets the confidence of this Hostname.  # noqa: E501


        :return: The confidence of this Hostname.  # noqa: E501
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this Hostname.


        :param confidence: The confidence of this Hostname.  # noqa: E501
        :type: int
        """

        self._confidence = confidence

    @property
    def deleted(self):
        """Gets the deleted of this Hostname.  # noqa: E501


        :return: The deleted of this Hostname.  # noqa: E501
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """Sets the deleted of this Hostname.


        :param deleted: The deleted of this Hostname.  # noqa: E501
        :type: bool
        """

        self._deleted = deleted

    @property
    def first_seen(self):
        """Gets the first_seen of this Hostname.  # noqa: E501


        :return: The first_seen of this Hostname.  # noqa: E501
        :rtype: datetime
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this Hostname.


        :param first_seen: The first_seen of this Hostname.  # noqa: E501
        :type: datetime
        """

        self._first_seen = first_seen

    @property
    def hostname(self):
        """Gets the hostname of this Hostname.  # noqa: E501


        :return: The hostname of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this Hostname.


        :param hostname: The hostname of this Hostname.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def id(self):
        """Gets the id of this Hostname.  # noqa: E501


        :return: The id of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Hostname.


        :param id: The id of this Hostname.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def ip_count(self):
        """Gets the ip_count of this Hostname.  # noqa: E501


        :return: The ip_count of this Hostname.  # noqa: E501
        :rtype: int
        """
        return self._ip_count

    @ip_count.setter
    def ip_count(self, ip_count):
        """Sets the ip_count of this Hostname.


        :param ip_count: The ip_count of this Hostname.  # noqa: E501
        :type: int
        """

        self._ip_count = ip_count

    @property
    def is_prime(self):
        """Gets the is_prime of this Hostname.  # noqa: E501


        :return: The is_prime of this Hostname.  # noqa: E501
        :rtype: bool
        """
        return self._is_prime

    @is_prime.setter
    def is_prime(self, is_prime):
        """Sets the is_prime of this Hostname.


        :param is_prime: The is_prime of this Hostname.  # noqa: E501
        :type: bool
        """

        self._is_prime = is_prime

    @property
    def last_seen(self):
        """Gets the last_seen of this Hostname.  # noqa: E501


        :return: The last_seen of this Hostname.  # noqa: E501
        :rtype: datetime
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this Hostname.


        :param last_seen: The last_seen of this Hostname.  # noqa: E501
        :type: datetime
        """

        self._last_seen = last_seen

    @property
    def max_confidence(self):
        """Gets the max_confidence of this Hostname.  # noqa: E501


        :return: The max_confidence of this Hostname.  # noqa: E501
        :rtype: int
        """
        return self._max_confidence

    @max_confidence.setter
    def max_confidence(self, max_confidence):
        """Sets the max_confidence of this Hostname.


        :param max_confidence: The max_confidence of this Hostname.  # noqa: E501
        :type: int
        """

        self._max_confidence = max_confidence

    @property
    def name_type(self):
        """Gets the name_type of this Hostname.  # noqa: E501


        :return: The name_type of this Hostname.  # noqa: E501
        :rtype: int
        """
        return self._name_type

    @name_type.setter
    def name_type(self, name_type):
        """Sets the name_type of this Hostname.


        :param name_type: The name_type of this Hostname.  # noqa: E501
        :type: int
        """

        self._name_type = name_type

    @property
    def org_id(self):
        """Gets the org_id of this Hostname.  # noqa: E501


        :return: The org_id of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Hostname.


        :param org_id: The org_id of this Hostname.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and org_id is None:  # noqa: E501
            raise ValueError("Invalid value for `org_id`, must not be `None`")  # noqa: E501

        self._org_id = org_id

    @property
    def perspective(self):
        """Gets the perspective of this Hostname.  # noqa: E501


        :return: The perspective of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._perspective

    @perspective.setter
    def perspective(self, perspective):
        """Sets the perspective of this Hostname.


        :param perspective: The perspective of this Hostname.  # noqa: E501
        :type: str
        """

        self._perspective = perspective

    @property
    def perspective_name(self):
        """Gets the perspective_name of this Hostname.  # noqa: E501


        :return: The perspective_name of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._perspective_name

    @perspective_name.setter
    def perspective_name(self, perspective_name):
        """Sets the perspective_name of this Hostname.


        :param perspective_name: The perspective_name of this Hostname.  # noqa: E501
        :type: str
        """

        self._perspective_name = perspective_name

    @property
    def status(self):
        """Gets the status of this Hostname.  # noqa: E501


        :return: The status of this Hostname.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Hostname.


        :param status: The status of this Hostname.  # noqa: E501
        :type: str
        """
        allowed_values = ["None", "Investigate", "In-progress", "Reviewed", "Resolved"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def tags(self):
        """Gets the tags of this Hostname.  # noqa: E501


        :return: The tags of this Hostname.  # noqa: E501
        :rtype: object
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Hostname.


        :param tags: The tags of this Hostname.  # noqa: E501
        :type: object
        """

        self._tags = tags

    @property
    def target_temptation(self):
        """Gets the target_temptation of this Hostname.  # noqa: E501


        :return: The target_temptation of this Hostname.  # noqa: E501
        :rtype: int
        """
        return self._target_temptation

    @target_temptation.setter
    def target_temptation(self, target_temptation):
        """Sets the target_temptation of this Hostname.


        :param target_temptation: The target_temptation of this Hostname.  # noqa: E501
        :type: int
        """

        self._target_temptation = target_temptation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Hostname):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Hostname):
            return True

        return self.to_dict() != other.to_dict()
