# coding: utf-8

"""
    Randori API

    Endpoints accessible using API tokens  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@randori.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from randori_api.configuration import Configuration


class PathsDataSchema(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'edges': 'dict(str, EdgeSchema)',
        'nodes': 'dict(str, NodeSchema)',
        'paths': 'list[list[str]]'
    }

    attribute_map = {
        'edges': 'edges',
        'nodes': 'nodes',
        'paths': 'paths'
    }

    def __init__(self, edges=None, nodes=None, paths=None, local_vars_configuration=None):  # noqa: E501
        """PathsDataSchema - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._edges = None
        self._nodes = None
        self._paths = None
        self.discriminator = None

        if edges is not None:
            self.edges = edges
        if nodes is not None:
            self.nodes = nodes
        if paths is not None:
            self.paths = paths

    @property
    def edges(self):
        """Gets the edges of this PathsDataSchema.  # noqa: E501


        :return: The edges of this PathsDataSchema.  # noqa: E501
        :rtype: dict(str, EdgeSchema)
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this PathsDataSchema.


        :param edges: The edges of this PathsDataSchema.  # noqa: E501
        :type: dict(str, EdgeSchema)
        """

        self._edges = edges

    @property
    def nodes(self):
        """Gets the nodes of this PathsDataSchema.  # noqa: E501


        :return: The nodes of this PathsDataSchema.  # noqa: E501
        :rtype: dict(str, NodeSchema)
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this PathsDataSchema.


        :param nodes: The nodes of this PathsDataSchema.  # noqa: E501
        :type: dict(str, NodeSchema)
        """

        self._nodes = nodes

    @property
    def paths(self):
        """Gets the paths of this PathsDataSchema.  # noqa: E501


        :return: The paths of this PathsDataSchema.  # noqa: E501
        :rtype: list[list[str]]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this PathsDataSchema.


        :param paths: The paths of this PathsDataSchema.  # noqa: E501
        :type: list[list[str]]
        """

        self._paths = paths

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PathsDataSchema):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PathsDataSchema):
            return True

        return self.to_dict() != other.to_dict()
