name: Post Mend to PR

on:
  repository_dispatch:
    types:
      - post-mend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mend:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - id: pr
      run: |
        issue=$(gh pr list --search "${{ github.event.client_payload.sha }}" --state merged --json number --jq ".[0].number")
        echo "issue=$issue" >>$GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add PR Comment
      uses: mshick/add-pr-comment@v2
      with:
        issue: ${{ steps.pr.outputs.issue }}
        message: ${{ github.event.client_payload.message }}
        allow-repeats: true
